### ISSUE TITLE
User Story #1

### ISSUE THREAD

**Issue by EarthToAbigail** [EarthToAbigail/FAC_Community#1]
As a user, I want to:

- Visit the Founders & Coders Community website and login with my github account

So that:

- I can join a platform that is exclusive to the FAC community around the World.

Acceptance Criteria:

- [x] Home page
- [x] Login with Github
- [ ] Accepting input from user to know which campus he/she is part of
- [x] Check that users are part of `Founders and Coders` organization on Github, if not, log them out
- [ ] Save users in database
