### ISSUE TITLE
User Story #3

### ISSUE THREAD

**Issue by EarthToAbigail** [EarthToAbigail/FAC_Community#3]
As a user, I want to:

- Have access to my personal editing page
- Import and save media into the app

So that:

- I can create records of specific moments within my Founders and Coders experience.
- I can add pictures or videos to the moments I edit
- I can make these moments public if I wish to share them

Acceptance Criteria:

- [ ] Editing page template (sketch book or blog style)
- [ ] Import photos/media functionality
- [ ] Share publicly functionality
- [ ] Save moments in database
